### ISSUE TITLE
How to activate slide mode on this plugin?

### ISSUE THREAD

**Issue by hazemhagrass** [pebois/phonegap-plugin-PDFViewer#2]
Hi,
first thanks a lot for your great efforts, but I'm wondering how to use pdf slide mode through your plugin?
this is easy by make the viewer displaying only single page then navigate through pages but I don't know how I can make this with your plugin. is this implemented or what?

**Comment by pebois** [comment]
Hi, not for the moment.
This plugin use the default pdf viewer loaded by the UIWebView.
For paging/navigation, i will have to implement my own PDF viewer component.

**Comment by hazemhagrass** [comment]
Thanks a lot for help

On Thu, Jan 30, 2014 at 3:41 PM, Manu notifications@github.com wrote:

> Hi, not for the moment.
> This plugin use the default pdf viewer loaded by the UIWebView.
> For paging/navigation, i will have to implement my own PDF viewer
> component.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/pebois/phonegap-plugin-PDFViewer/issues/2#issuecomment-33688171
> .

## 

Thanks a lot
Hazem Mohammed Hagrass
