### ISSUE TITLE
Open file with new url scheme

### ISSUE THREAD

**Issue by cellk** [pebois/phonegap-plugin-PDFViewer#3]
Bonjour,

Merci pour votre excellent plugin. 
Est-il possible d'utiliser votre plugin afin d'ouvrir des fichiers dont les liens sont de type cdvfile://localhost/persistent/file.pdf par cordova (release 2 fevr 2014)?
Avez-vous l'intention de le mettre a jour?

Kenny

http://cordova.apache.org/news/2014/02/10/plugins-release.html

**Comment by pebois** [comment]
Bonjour,
Je vais faire évoluer ce plugin, sous peu, pour gérer ce nouveau format.
Merci pour ce retour.

**Comment by pebois** [comment]
Bonjour,
Pour ne pas provoquer de dépendance avec le plugin cordova.file, la résolution du chemin cdvfile:// peut être faite en amont en utilisant la méthode resolveLocalFileSystemURL.
PDFViewer.open accepte les chemins absolus.
