### ISSUE TITLE
how to load local file?

### ISSUE THREAD

**Issue by queenyjina** [pebois/phonegap-plugin-PDFViewer#4]
cordova file path
/www/test.pdf

PDFViewer.open("file://www/test.pdf","test.pdf", function (msg) {
    console.log(msg);
});

i'm not load~!!!

please help me~!

**Comment by pebois** [comment]
if your pdf is in the www directory (from the root directory of your project), just call :

```
PDFViewer.open("www/test.pdf","test.pdf", function (msg) {
```

**Comment by git-neelesh** [comment]
I tried with all types ,

```
   PDFViewer.open("/android/www/107201414317RFFlow.pdf","sample.pdf", function (msg) {
        alert(msg);
    });

    PDFViewer.open("www/107201414317RFFlow.pdf","sample.pdf", function (msg) {
        alert(msg);
    });

    PDFViewer.open("./107201414317RFFlow.pdf","sample.pdf", function (msg) {
        alert(msg);
    });
```

Even tried with more combination of path.
and file is inside www folder. still giving me error: Preview . any suggestion?

**Comment by pebois** [comment]
Are you trying on android or iOS ?

**Comment by git-neelesh** [comment]
Android!

**Comment by git-neelesh** [comment]
oops, its only for IOS?

**Comment by git-neelesh** [comment]
I found http://plugreg.com/plugin/pebois/phonegap-plugin-PDFViewer

**Comment by pebois** [comment]
yes only for iOS

**Comment by git-neelesh** [comment]
http://plugreg.com/plugin/pebois/phonegap-plugin-PDFViewer here mentioned all supported OS.

**Comment by pebois** [comment]
Absolutely not, take a look again. There is just one tick on iOS.

**Comment by git-neelesh** [comment]
Ohh, My mistake. tick was very small :) any roadmap for android support?

**Comment by pebois** [comment]
not at this time sorry

**Comment by git-neelesh** [comment]
Np, thanks!
